import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background:                    '#0e0e13',
        surface:                       '#0e0e13',
        'surface-dim':                 '#0e0e13',
        'surface-container-lowest':    '#000000',
        'surface-container-low':       '#131318',
        'surface-container':           '#19191f',
        'surface-container-high':      '#1f1f26',
        'surface-container-highest':   '#25252c',
        'surface-bright':              '#2c2b33',
        'surface-variant':             '#25252c',
        'surface-tint':                '#de8eff',
        'inverse-surface':             '#fbf8ff',
        'on-surface':                  '#f8f5fd',
        'on-surface-variant':          '#acaab1',
        'inverse-on-surface':          '#55545a',
        primary:                       '#de8eff',
        'primary-container':           '#d779ff',
        'primary-fixed':               '#d779ff',
        'primary-fixed-dim':           '#cf62ff',
        'primary-dim':                 '#b90afc',
        'on-primary':                  '#4f006e',
        'on-primary-container':        '#3d0056',
        'on-primary-fixed':            '#000000',
        'on-primary-fixed-variant':    '#4b0069',
        'inverse-primary':             '#9900d1',
        secondary:                     '#00f4fe',
        'secondary-container':         '#00696e',
        'secondary-fixed':             '#00f4fe',
        'secondary-fixed-dim':         '#00e5ee',
        'secondary-dim':               '#00e5ee',
        'on-secondary':                '#00575b',
        'on-secondary-container':      '#dffdff',
        'on-secondary-fixed':          '#004346',
        'on-secondary-fixed-variant':  '#006266',
        tertiary:                      '#bcff5f',
        'tertiary-container':          '#a2f31f',
        'tertiary-fixed':              '#a2f31f',
        'tertiary-fixed-dim':          '#95e400',
        'tertiary-dim':                '#95e400',
        'on-tertiary':                 '#3d6100',
        'on-tertiary-container':       '#365700',
        'on-tertiary-fixed':           '#294300',
        'on-tertiary-fixed-variant':   '#3d6200',
        error:                         '#ff6e84',
        'error-container':             '#a70138',
        'error-dim':                   '#d73357',
        'on-error':                    '#490013',
        'on-error-container':          '#ffb2b9',
        outline:                       '#76747b',
        'outline-variant':             '#48474d',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm:      '0.5rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'sans-serif'],
        body:     ['var(--font-body)', 'sans-serif'],
        label:    ['var(--font-body)', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}

export default config
